on:
  push:
    paths:
      - 'my_tester.sh'
      - '*.yml'
  workflow_dispatch:

env:
  TESTS_COUNT: 0

jobs:
  update-readme:
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get test count and set env variable
        run: |
          COUNT=$(cat my_tester.sh | grep -c "execute \"")
          echo "TESTS_COUNT=$COUNT" >> $GITHUB_ENV

      - name: Update link pattern
        run: |
          sed -i "s/!\[image\](https:\/\/img\.shields\.io\/badge\/Test%20Count-[0-9]*-blue)/![image](https:\/\/img\.shields\.io\/badge\/Test%20Count-$COUNT-blue)/g" README.md